@extends('layouts.app')

@section('title','Please Login')

@section('content')
<style >
    .navbar{
        display: none !important;
    }
</style>
    {{--    <table id="requestsTable">--}}
    <table>
        <tr>
            <td class="col-md-9">
                <p>
                    <b>Report Generated For: Bolger Direct</b><br>
                    668 Kasota Ave SE<br>
                    Minneapolis, MN 55414
                </p>
            </td>
            <td></td>
            <td class="col-md-3">
                <p>
                    <b>Report Generated By: {{\Illuminate\Support\Facades\Auth::user()->name}}
                    </b><br>
                    <b>Generated On: {{date('m/d/Y h:i:s', time())}}</b><br><br>
                </p>
            </td>
        </tr>
    </table>
<br>
    <table id="requestsTable" class="table table-striped table-hover" style="table-layout:fixed;">
        <thead class="thead-dark">
            <tr>
                <th style="width:10%">
                    Date
                </th>
                <th style="width:10%">
                    Request Type
                </th>
                <th style="width:10%">
                    Change Type
                </th>
                <th style="width:30%">
                    Description
                </th>
                <th style="width:10%">
                    Requested By
                </th>
                <th style="width:10%">
                    Approved By
                </th>
                <th style="width:10%">
                    Reviewed By
                </th>
                <th style="width:10%">
                    Completed By
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach($requests as $req)
                <tr><td id="dateTd">
                        {{$req->created_at}}
                    </td>
                    <td>
                        {{$req->requestType}}
                    </td>
                    <td>
                        {{$req->ChangeType}}
                    </td>
                    <td>
                        {{$req->description}}
                    </td>
                    <td>
                        {{$req->requestorID}}
                    </td>
                    <td>
                        {{$req->approverID ?? 'pending'}}
                    </td>
                    <td>
                        {{$req->reviewerID ?? 'pending'}}
                    </td>
                    <td>
                        {{$req->completedBy ?? 'pending'}}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection
